@Entry
@Component
struct RegPage {


  build() {
    Column(){
      Swiper(){
       Image('https://img2.baidu.com/it/u=1409005732,3786216107&fm=253&app=120&size=w931&n=0&f=JPE2dcc36ddaafc6ae2fb96c4bae75')
         .width('100%')
        Image('https://img2.baidu.com/it/u=1409005732,3786216107&fm=253&app=120&size=w931&n=0&f=JPE2dcc36ddaafc6ae2fb96c4bae75')
          .width('100%')
        Image('https://img2.baidu.com/it/u=1409005732,3786216107&fm=253&app=120&size=w931&n=0&f=JPE2dcc36ddaafc6ae2fb96c4bae75')
          .width('100%')
        Image('https://img2.baidu.com/it/u=1409005732,3786216107&fm=253&app=120&size=w931&n=0&f=JPE2dcc36ddaafc6ae2fb96c4bae75')
          .width('100%')
        Image('https://img2.baidu.com/it/u=1409005732,3786216107&fm=253&app=120&size=w931&n=0&f=JPE2dcc36ddaafc6ae2fb96c4bae75')
          .width('100%')
      }.autoPlay(true)
    }
    .height('100%')
    .width('100%')
  }
}